export const CONSTRUCTION_STAGES = [
  'Enabling Works',
  'Substructure – Excavation',
  'Substructure – Piling',
  'Substructure – Foundations',
  'Lift Pits',
  'Substructure – Basement Construction (including Lift Pits)',
  'Basement Waterproofing',
  'Substructure – Below Ground Building Services',
  'Capping Beam / Slab',
  'Ground Floor Slab & DPC',
  'Podium / Transfer Slab',
  'External Wall Construction',
  'Roof Structure',
  'Roof Waterproofing',
  'Internal Wall Construction',
  'Ventilation',
  'Heating Services',
  'Water Services',
  'Electrical Services',
  'Cavity Barriers',
  'Firestopping',
  'Means of Escape',
  'Guarding / Protection from Falls',
  'Window and Door Installation',
  'Balcony Installation',
  'Chimneys and Flues',
  'Cladding / External Walls',
  'Drainage',
  'Drains Test',
  'Decorating / Woodwork',
  'Ground Floors',
  'Stairs',
  'Driveways and Paving',
  'Externals Complete',
  'Balconies',
  'Basements',
  'Roofs',
  'Windows and Doors'
] as const;

export type ConstructionStage = typeof CONSTRUCTION_STAGES[number];